udistrital/sga_cliente_admisiones_mf

- README.md
- Esta Pull Request actualiza el archivo README.md
---
udistrital/sga_documentacion#123
> Feature/issue#123 Actualizar README

- src/app/components/codificacion-module/codificacion-routing.module.ts
- src/app/components/codificacion-module/codificacion.module.ts
- src/app/components/codificacion-module/components/reporte-codificacion/reporte-codificacion.component.html
- src/app/components/codificacion-module/components/reporte-codificacion/reporte-codificacion.component.scss
- src/app/components/codificacion-module/components/reporte-codificacion/reporte-codificacion.component.spec.ts
- src/app/components/codificacion-module/components/reporte-codificacion/reporte-codificacion.component.ts
- src/app/components/repotes-inscripciones/repotes-inscripciones.component.html
- src/app/components/repotes-inscripciones/repotes-inscripciones.component.ts
- src/app/models/reportes/tipo-reportes-inscripciones.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- yarn.lock
udistrital/sga_documentacion#164
Dentro de el componente de reportes dinámicos, se realizan las modificaciones correspondientes para poder desplegar un  nuevo reporte, que necesita solo el periodo y el nivel para realizar la consulta de el reporte general.
> Feat: Creación reporte dinamico para consulta general de proyectos por periodo y nivel

- .drone.yml
- angular.json
- package.json
Actualizar para despliegue udistrital/sga_documentacion#179
> feat: Actualizar para despliegue udistrital/sga_documentacion#179 Feature/issue#179

- src/app/components/evalucion-documentos-inscritos/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
udistrital/sga_documentacion#194
> feat: Ajuste respuesta MID 

- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/components/codificacion-module/components/reporte-codificacion/reporte-codificacion.component.ts
- src/app/components/evalucion-documentos-inscritos/evaluacion-documentos-inscritos/evaluacion-documentos-inscritos.component.ts
- src/app/components/evalucion-documentos-inscritos/view-formacion_academica/view-formacion_academica.component.ts
- src/app/components/evalucion-documentos-inscritos/view-produccion_academica/view-produccion_academica.component.ts
- src/app/components/lista-proyectos-aspirantes/lista-proyectos-aspirantes.component.ts
- src/app/components/listado-aspirantes/listado_aspirantes/listado_aspirante.component.ts
- src/app/components/repotes-inscripciones/repotes-inscripciones.component.ts
feat: Ajuste respuesta MID udistrital/sga_documentacion#194
> feat: Ajuste respuesta MID udistrital/sga_documentacion#194

- src/app/components/liquidacion/liquidacion-table/liquidacion-table.component.html
- src/app/components/liquidacion/liquidacion-table/liquidacion-table.component.scss
- src/app/components/liquidacion/liquidacion-table/liquidacion-table.component.spec.ts
- src/app/components/liquidacion/liquidacion-table/liquidacion-table.component.ts
Corrección errores de ejecución
> Fix: merge feature/issues-207

- src/app/app-routing.module.ts
- src/app/components/codificacion-module/codificacion-routing.module.ts
- Ajuste de nombre de rutas en micro clientes (refactoring)
---
udistrital/sga_documentacion#196
> Feat: Ajuste de nombre de rutas en micro clientes (refactoring)

- src/app/components/crieterios-admisiones-proyectos/criterio_admision/criterio_admision.component.ts
- src/environments/environment.development.ts
- src/environments/environment.ts
udistrital/sga_documentacion#218
Se soluciona el bug que evitaba la eliminación de criterios para un proyecto curricular al deseleccionarlos.
> fix: solución error que evitaba la elimianción de requisitos

- src/app/components/cargue-snp/cargue-snp.component.html
- src/app/components/cargue-snp/cargue-snp.component.scss
- src/app/components/cargue-snp/cargue-snp.component.ts
- src/app/components/listado-aspirantes-pregrado/listado-aspirantes-pregrado.component.html
- src/app/components/listado-aspirantes-pregrado/listado-aspirantes-pregrado.component.scss
- src/app/components/listado-aspirantes-pregrado/listado-aspirantes-pregrado.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- yarn.lock
https://github.com/udistrital/sga_documentacion/issues/190
> feat: udistrital/sga_documentacion#190 Integración para pantallas de cargue SNP y listar aspirantes para pregrado

- src/app/components/evalucion-aspirante-pregrado/evalucion-aspirante.component.html
- src/app/components/evalucion-aspirante-pregrado/evalucion-aspirante.component.ts
https://github.com/udistrital/sga_documentacion/issues/226
> feat: udistrital/sga_documentacion#226 Carga data inicial del filtro inicial

- src/app/components/liquidacion/liquidacion-historico/liquidacion-historico.component.html
- src/app/components/liquidacion/liquidacion-historico/liquidacion-historico.component.ts
- src/app/components/liquidacion/liquidacion-table/liquidacion-table.component.html
- src/app/components/liquidacion/liquidacion-table/liquidacion-table.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
https://github.com/udistrital/sga_documentacion/issues/225
> feat: udistrital/sga_documentacion#225 Refactorización de la tabla de liquidaciones en liquidacion-historico

- .drone.yml
- .husky/build_develop.js
- .husky/pre-push
- package-lock.json
- package.json
- yarn.lock
feat: Implementación script Husky udistrital/sga_documentacion#239
> feat: Implementación script Husky udistrital/sga_documentacion#239

- src/app/components/liquidacion-recibos/liquidacion-recibos.component.html
- src/app/components/liquidacion-recibos/liquidacion-recibos.component.ts
- src/app/components/liquidacion/liquidacion-recibos/liquidacion-recibos.component.html
- src/app/components/liquidacion/liquidacion-recibos/liquidacion-recibos.component.ts
- src/environments/environment.development.ts
- src/environments/environment.ts
[feat:](https://github.com/udistrital/sga_cliente_admisiones_mf/commit/82a3f32842156e3f74bd89b6f06349a4e3f678a4) https://github.com/udistrital/sga_documentacion/issues/240 
Implementación de notificación generación recibos de pago para pregrado y posgrado
> feat: udistrital/sga_documentacion#240

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/correo-institucional/correo-institucional.component.html
- src/app/components/correo-institucional/correo-institucional.component.spec.ts
- src/app/components/correo-institucional/correo-institucional.component.ts
feat: Creación componente correo institucional udistrital/sga_documentacion#264
> feat: Creación componente correo institucional udistrital/sga_documentacion#264

- .gitignore
- extra-webpack.config.js
- package-lock.json
- package.json
- src/app/components/evalucion-documentos-inscritos/view-descuento_academico/view-descuento_academico.component.ts
- src/app/constants/secret-key.ts
- src/environments/environment.ts
- src/utils/util-encrypt.ts
- tsconfig.app.json
https://github.com/udistrital/sga_documentacion/issues/311
> feat: udistrital/sga_documentacion#311 Modificación del lugar de almacenamiento del secret key para encriptar y recuperación persona_id

- src/app/components/cargue-snp/cargue-snp.component.scss
- src/app/components/cargue-snp/cargue-snp.component.ts
https://github.com/udistrital/sga_documentacion/issues/328
> feat: udistrital/sga_documentacion#328 Actualización del JSON generado de detalle de evaluación ICFES

- src/app/components/evalucion-aspirante-pregrado/evalucion-aspirante.component.html
- src/app/components/evalucion-aspirante-pregrado/evalucion-aspirante.component.scss
- src/app/components/evalucion-aspirante-pregrado/evalucion-aspirante.component.ts
- src/app/components/liquidacion/liquidacion-historico/liquidacion-historico.component.ts
- src/app/components/listado-admitidos/listado-admitidos/listado-admitidos.component.html
- src/app/components/listado-admitidos/listado-admitidos/listado-admitidos.component.ts
- src/app/components/listado-admitidos/tabla-listado-aspirantes/tabla-listado-aspirantes.component.html
- src/app/components/listado-admitidos/tabla-listado-aspirantes/tabla-listado-aspirantes.component.scss
- src/app/components/listado-admitidos/tabla-listado-aspirantes/tabla-listado-aspirantes.component.ts
- src/app/components/listado-oficializados/listado-oficializados.component.html
- src/app/components/listado-oficializados/listado-oficializados.component.scss
- src/app/components/listado-oficializados/listado-oficializados.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
https://github.com/udistrital/sga_documentacion/issues/369
> feat: udistrital/sga_documentacion#369 Corrección de errores en pantallas 

- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/evaluacion-aspirantes.component.html
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/evaluacion-aspirantes.component.scss
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/components/evalucion-aspirante-pregrado/evalucion-aspirante.component.html
- src/app/components/evalucion-aspirante-pregrado/evalucion-aspirante.component.ts
https://github.com/udistrital/sga_documentacion/issues/450
> feat: udistrital/sga_documentacion#450 Estabilizacion de proceso de inscripcion y admision para pregrado

- src/app/components/suite-programa/def_suite_inscrip_programa/def-suite-inscrip-programa.component.html
- src/app/components/suite-programa/def_suite_inscrip_programa/def-suite-inscrip-programa.component.scss
- src/app/components/suite-programa/def_suite_inscrip_programa/def-suite-inscrip-programa.component.ts
- src/app/components/suite-programa/def_suite_inscrip_programa/def_tags_por_programa.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
https://github.com/udistrital/sga_documentacion/issues/463
> feat: udistrital/sga_documentacion#463 Modificaciones de tags

- package-lock.json
- package.json
- src/app/components/asignacion-cupos-proyectos/dinamicform/dinamicform.component.html
- src/app/components/asignacion-cupos-proyectos/dinamicform/dinamicform.component.ts
- src/app/components/asignar-documentos-descuentos/select-documento-proyecto/select-documento-proyecto.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- yarn.lock
fix: Funcionalidad del checkbox arreglada udistrital/sga_documentacion#494
> fix: Funcionalidad del checkbox arreglada udistrital/sga_documentacion#494

- .drone.yml
management: Ajuste de bucket para despliegue en ambiente de prod
> management: Ajuste de bucket para despliegue en ambiente de prod

- src/app/components/tipo-inscripcion/lista-tipo-inscripcion/lista-tipo-inscripcion.component.html
- src/app/components/tipo-inscripcion/lista-tipo-inscripcion/lista-tipo-inscripcion.component.scss
- src/app/components/tipo-inscripcion/lista-tipo-inscripcion/lista-tipo-inscripcion.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- Porder habilitar o deshabilitar un tipo de inscripcion ✅ 
---
udistrital/sga_documentacion#434
> feat: habilitar y deshabilitar un tipo de inscripcion 

- src/environments/environment.development.ts
- src/environments/environment.production.ts
- Se actualizaron las URLs de los servicios en los archivos de entorno de desarrollo y producción para corregir errores de conexión.
---
udistrital/sga_documentacion#523
> refactor: actualizar URLs de servicios

- src/environments/environment.production.ts
Management : Update environment.production.ts
> Management : Update environment.production.ts

- src/app/app.module.ts
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/evaluacion-aspirantes.component.ts
- src/app/components/administrar-criterios-admisiones/administrador-criterios/administrador-criterios.component.html
- src/app/components/administrar-criterios-admisiones/administrador-criterios/administrador-criterios.component.ts
- src/app/components/administrar-criterios-admisiones/dialogo-criterios/dialogo-criterios.component.html
- src/app/components/administrar-criterios-admisiones/dialogo-criterios/dialogo-criterios.component.ts
- src/app/components/listado-aspirantes/listado_aspirantes/listado_aspirante.component.html
- Correccion de bugs en `Administrar criterios de admision`.
- Correccion de error de carga de `Listado de aspirantes`.
---
udistrital/sga_documentacion#523
> refactor: correccion de bugs 2

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/evaluacion-aspirantes.component.html
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/tabla-criterios-estudiantes/tabla-criterios-estudiantes.component.html
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/tabla-criterios-estudiantes/tabla-criterios-estudiantes.component.scss
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/tabla-criterios-estudiantes/tabla-criterios-estudiantes.component.spec.ts
- src/app/components/Evaluacion-aspirante/evaluacion-aspirantes/tabla-criterios-estudiantes/tabla-criterios-estudiantes.component.ts
- src/app/components/asignar-documentos-descuentos/asignar_documentos_descuentos/asignar_documentos_descuentos.component.html
- src/app/directives/is-granted.directive.ts
- src/app/services/any.service.ts
- yarn.lock
- Muestra el tab de documentos de descuentos validando antes el rol del usuario.
- Integracion de la tabla en evaluacion de aspirantes.
- Soporta listar estudiantes cuando no se tienen aun evaluaciones.
---
udistrital/sga_documentacion#535
> refactor: correccion de bugs 3

- src/app/components/reportes/reportes.component.html
- src/app/components/reportes/reportes.component.ts
- src/assets/i18n/es.json
Feat: Ajustes traducción español y unificacion de estado inscripción/admisión udistrital/sga_documentacion#524
> Feat: Ajustes traducción español y unificacion de estado inscripción/admisión udistrital/sga_documentacion#524

- src/app/components/asignacion-cupos-proyectos/asignacion_cupos/crud-asignacion_cupo/crud-asignacion_cupo.component.html
- src/app/components/asignacion-cupos-proyectos/asignacion_cupos/crud-asignacion_cupo/crud-asignacion_cupo.component.scss
- src/app/components/asignacion-cupos-proyectos/asignacion_cupos/crud-asignacion_cupo/crud-asignacion_cupo.component.ts
- yarn.lock
- loading la definicion de un tipo de cupo.
- Correccion de bug al cargar el soporte, se estaba llamando la funcion de eliminarCupo()
---
udistrital/sga_documentacion#535
> fix: `/asignacion-cupos`
